import mongoose from 'mongoose';

const FileSchema = new mongoose.Schema({
  fileId: mongoose.Schema.Types.ObjectId,
  filename: String,
  originalName: String,
  contentType: String,
  size: Number,
  uploadDate: Date,
  url: String,
  description: String,
  tags: [String],
}, { _id: false });

const AmenitySchema = new mongoose.Schema({
  name: String,
  image: String,
}, { _id: true });

const NearbyPlaceSchema = new mongoose.Schema({
  name: String,
  location: String,
  distance: String,
}, { _id: true });

const ReviewSchema = new mongoose.Schema({
  user: String,
  rating: {
    type: Number,
    min: 1,
    max: 5,
  },
  date: String,
  comment: String,
  userPhoneNumber: String,
}, { _id: true });

const FloorConfigurationSchema = new mongoose.Schema({
  floor: String,
  dedicatedCabin: {
    enabled: Boolean,
    readyToMove: Boolean,
    readyForFitOut: Boolean,
    availableFrom: Date,
    timeline: String,
    seats: String,
    pricePerSeat: String,
    pricePerSqft: String,
    billableUnits: String,
  },
  dedicatedFloor: {
    enabled: Boolean,
    readyToMove: Boolean,
    readyForFitOut: Boolean,
    availableFrom: Date,
    timeline: String,
    seats: String,
    pricePerSeat: String,
    pricePerSqft: String,
    billableUnits: String,
  },
}, { _id: false });

const ResidentialPropertySchema = new mongoose.Schema({
  selectedType: String,
  apartmentType: String,
  bhkType: String,
  propertySize: String,
  carpetArea: String,
  floor: String,
  totalFloors: String,
  facing: String,
  propertyAge: String,
  availableFor: String,
  expectedRent: String,
  isNegotiable: Boolean,
  expectedDeposit: String,
  monthlyMaintenance: String,
  originalPrice: String,
  discountedPrice: String,
  additionalPrice: String,
  availableFrom: String,
  furnishing: String,
  parking: String,
  propertyName: String,
  category: String,
  Category: String,
  address: {
    country: String,
    state: String,
    district: String,
    city: String,
    locality: String,
    street: String,
    pincode: String,
    landmark: String,
  },
  coordinates: {
    latitude: Number,
    longitude: Number,
    lat: Number,
    lng: Number,
  },
  bathrooms: Number,
  balconies: Number,
  whoWillShow: String,
  nonVegAllowed: Boolean,
  gatedSecurity: Boolean,
  gym: Boolean,
  directionsTip: String,
  currentSituation: String,
  waterSupply: String,
  amenities: [AmenitySchema],
  selectedFloors: [String],
  status: String,
  createdBy: mongoose.Schema.Types.ObjectId,
  views: Number,
  inquiries: Number,
  verificationStatus: String,
  badge: String,
  date_added: String,
  nearbyPlaces: {
    school: [NearbyPlaceSchema],
    hospital: [NearbyPlaceSchema],
    hotel: [NearbyPlaceSchema],
    business: [NearbyPlaceSchema],
  },
  ratings: {
    overall: Number,
    totalRatings: Number,
    breakdown: Object,
    whatsGood: [String],
    whatsBad: [String],
  },
  reviews: [ReviewSchema],
  propertyType: String,
  location: String,
  sellerPhoneNumber: String,
  isUnderManagement: String,
  facilities: [String],
  floorConfigurations: [FloorConfigurationSchema],
  interiorImages: [FileSchema],
  propertyVideos: [FileSchema],
  featuredImage: FileSchema,
  publishedAt: Date,
  updatedBy: mongoose.Schema.Types.ObjectId,
  
  // Legacy fields for backward compatibility
  state_name: String,
  city: String,
  name: String,
  images: [String],
  featuredImageUrl: String,
  is_verified: Boolean,
  layer_location: String,
  location_district: String,
  floors_available: [String],
  floorPlans: {
    type: Map,
    of: [String],
  },
  price_per_desk: Number,
  price_per_sqft: Number,
  no_of_seats: Number,
}, {
  timestamps: true,
  strict: false,
  collection: 'residentialproperties',  // Changed to match actual MongoDB collection name (lowercase)
});

export default mongoose.models.ResidentialProperty || mongoose.model('ResidentialProperty', ResidentialPropertySchema);
